---
title: "ErrorB Correction"
author: "Ziwei Crystal Zang"
date: "9/30/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(spatstat.utils)
library(mosaic)
library(cranium)

library(dplyr)
library(broom)
library(tidyverse)
library(gridExtra)
library(mosaic)
```

# new functions
```{r}
print_one_plot <- function(x = ro_brain_yt_1, title = "Sample Plot"){
    setwd("/Users/czang/Documents/cranium/sample_plot/correctionB/youtoo_15")
    wd <- getwd()
    png(paste(wd, "/",title, ".png", sep=""), width = 900, height = 300)
    plot2d(x , title = title) #output image with dimension: 900*300
    dev.off()
}   


calc_quad.coef <- function(x = ro_data){
 ro_data <- add_attr(ro_data)
  quad_model <- attr(ro_data, "quad_mod_xz") #quadratic model y = x^2 + x
  quad.coef= round((summary(quad_model)$coefficients["I(x^2)", "Estimate"]), 5)

  ro_model <- attr(ro_data, "quad_mod_xz")
  quad.coef = round((summary(ro_model)$coefficients["I(x^2)", "Estimate"]), 4)  #a
  return(quad.coef)
}

```


```{r}
#access PCA reoriented data for youtoo and wildtype
ro_brain_ls_yt <- readRDS(file = "/Users/czang/Desktop/processed_sample/ro_brain_ls_yt.rds") 

ro_brain_ls_wt <- readRDS(file = "/Users/czang/Desktop/processed_sample/ro_brain_ls_wt.rds")

#plot all samples 
#plot_all_sample(x=ro_brain_ls_wt ,type = "wildtype", wd = "/Users/czang/Documents/cranium/")
#plot_all_sample(x=ro_brain_ls_yt , type = "youtoo", wd = "/Users/czang/Documents/cranium/")
```

# start with one sample: youtoo 2
```{r}
#selecting sample from the list
#ro_brain_yt_3 <- ro_brain_ls_yt[[3]]
ro_brain_yt <- ro_brain_ls_yt[[2]]

plot2d(ro_brain_yt , title = "Youtoo Sample #1 - After PCA-step 1") #output image with dimension: 900*300

print_one_plot(x = ro_brain_yt, title = "Youtoo Sample #2 - After PCA-step 1")
```

#check for error A and make correction
```{r}
is_errorA(ro_brain_yt)

cA_ro_brain_yt <- correct_errorA(ro_brain_yt, threshold.n=0.5)

is_errorA(cA_ro_brain_yt)

plot2d(cA_ro_brain_yt , title = "Youtoo Sample #2 - After correction for errorA-step 2") #output image with dimension: 900*300

print_one_plot(x = cA_ro_brain_yt,  title = "Youtoo Sample #2 - After correction for errorA-step 2")
```

# check for each iteration of the correction
#Function: correct_errorB

```{r}
#ro_data <- cA_ro_brain_yt

cB_brain_yt <- correct_errorB.tbl_brain(cA_ro_brain_yt)
print_one_plot(x = cB_brain_yt,  title = "Youtoo Sample #2 - After 1 correction for errorB-step 3")


cB2_brain_yt <- correct_errorB.tbl_brain(cB_brain_yt)
print_one_plot(x = cB2_brain_yt,  title = "Youtoo Sample #2 - After 2 corrections for errorB-step 4")

cB3_brain_yt <- correct_errorB.tbl_brain(cB2_brain_yt)
print_one_plot(x = cB3_brain_yt,  title = "Youtoo Sample #2 - After 3 corrections for errorB-step 5")


cB4_brain_yt <- correct_errorB.tbl_brain(cB3_brain_yt)
print_one_plot(x = cB4_brain_yt,  title = "Youtoo Sample #2 - After 4 corrections for errorB-step 6")



cB5_brain_yt <- correct_errorB.tbl_brain(cB4_brain_yt)
print_one_plot(x = cB5_brain_yt,  title = "Youtoo Sample #2 - After 5 corrections for errorB-step 7")


cB6_brain_yt <- correct_errorB.tbl_brain(cB5_brain_yt)
print_one_plot(x = cB6_brain_yt,  title = "Youtoo Sample #2 - After 6 corrections for errorB-step 8")


cB7_brain_yt <- correct_errorB.tbl_brain(cB6_brain_yt)
print_one_plot(x = cB7_brain_yt,  title = "Youtoo Sample #2 - After 7 corrections for errorB-step 9")

is_errorB.tbl_brain(cB8_brain_yt)
```



# build the pipeline
```{r}
#start with brain data that is tidied and pca reoriented
ro_brain_yt <- ro_brain_ls_yt[[2]]
x = ro_brain_yt


plot2d(x_step1 , title = "Youtoo Sample #2 - After correction for errorA-step 2") #output image with dimension: 900*300


pipeline_correctionAB <- function(x = ro_brain_yt, B.correct.n = 8){
  #check for error A
  if (is_errorA(x)){
    message("Detect error A")
    #make correction for error A
    x_step1 <- correct_errorA(x, threshold.n=0.5)
    #confirm correction is made 
    if (is_errorA(x_step1)){
      message("Error A correction failed. Return brain data before processing.")
      return(x)
    }else {
      message("Error A correction succeed.Data is corrected for error A.")
    }
  }else{
    #no error A, keep the original brain data
    message("Error A not detected")
    x_step1 <- x
  }
  
  #check for error B
  if (is_errorB(x_step1)){
     # there is errorB
     # make correction for error B
     x.list <- list()
     x.list[[1]] <- x_step1
     for (i in 2 : B.correct.n){
        x.list[[i]] <-  correct_errorB.tbl_brain(x.list[[i-1]])
     }
     x_step2 <- x.list[[B.correct.n]]
     if (is_errorB(x_step2)){
      message(paste("After performing errorB correction", B.correct.n, "times, error B is still detected, please increase the the B.correct.n parameter. Return brain data before processing."))
       return(x)
     }else{
       message(paste("After performing errorB correction", B.correct.n, "times, we successfully corrected brain data for error B. Return corrected brain data."))
       return(x.list[[B.correct.n]])
     }   
    }else{
    # there is no errorB
      message("Error B is not detected, return original brain data.")
    return(x_step1)
  }
}


is_errorB(x.list[[10]])
check <- correct_errorB.tbl_brain(x.list[[8]])
is_errorB.tbl_brain(check)

plot2d(check, title = "Youtoo Sample #2 - After correction for errorA-step 2") #output image with dimension: 900*300

```

# check the correction for several samples
```{r}
ro_brain_yt <- ro_brain_ls_yt[[10]]
plot2d(ro_brain_yt , title = "Youtoo Sample #3 - After correction for errorA-step 2") #output image with dimension: 900*300
#print_one_plot(x = ro_brain_yt, title = "Youtoo Sample #3 - After PCA-step 1")

co_ro_brain_yt <- pipeline_correctionAB(ro_brain_yt, B.correct.n = 20)
plot2d(co_ro_brain_yt , title = "Youtoo Sample #3 - After correction for errorA-step 2") #output image with dimension: 900*300
#print_one_plot(x = co_ro_brain_yt , title = "Youtoo Sample #3-After correction for errorA,B-step2")
```

# apply pipeline error correction for all youtoo samples
```{r}
co_ro_brain_yt <- list()
check_errorA_vector <- c()
check_errorB_vector <- c()
calc_quad_coef_xz_plane <- c()

for (i in (1:length(ro_brain_ls_yt))){
  x <- ro_brain_ls_yt[[i]]
  co_ro_brain_yt[[i]] <- pipeline_correctionAB(x, B.correct.n = 10)
  co_x <- co_ro_brain_yt[[i]]
  check_errorA_vector[i] <- is_errorA(co_x)
  check_errorB_vector[i] <- is_errorB(co_x)
  calc_quad_coef_xz_plane[i] <- calc_quad.coef(co_x)
}


plot_all_sample(x = co_ro_brain_yt , type = "youtoo", file_directory = "/Users/czang/Documents/cranium/Sample/YouToo", save_directory = "/Users/czang/Documents/cranium/sample_plot/")
  
#plot2d(co_x, title = "Youtoo Sample #15 - After correction for errorA-step 1") 

```

# check why correction B can't applied to youtoo sample 6
```{r}
x <- ro_brain_ls_yt[[15]]
plot2d(x, title = "Youtoo Sample #15 - After correction for errorA-step 1") 
print_one_plot(x = x,  title = "Youtoo Sample #15 - after PCA-step 1")

#co_x <- pipeline_correctionAB(x, B.correct.n = 10)
is_errorA(x)
cA_ro_brain_yt <- correct_errorA(x)
print_one_plot(x = cA_ro_brain_yt,  title = "Youtoo Sample #15 - After correction for errorA-step 2")

cB_brain_yt <- correct_errorB.tbl_brain(cA_ro_brain_yt)
print_one_plot(x = cB_brain_yt,  title = "Youtoo Sample #15 - After 1 correction for errorB-step 3")


cB2_brain_yt <- correct_errorB.tbl_brain(cB_brain_yt)
print_one_plot(x = cB2_brain_yt,  title = "Youtoo Sample #15 - After 2 corrections for errorB-step 4")

cB3_brain_yt <- correct_errorB.tbl_brain(cB2_brain_yt)
print_one_plot(x = cB3_brain_yt,  title = "Youtoo Sample #15 - After 3 corrections for errorB-step 5")


cB4_brain_yt <- correct_errorB.tbl_brain(cB3_brain_yt)
print_one_plot(x = cB4_brain_yt,  title = "Youtoo Sample #15 - After 4 corrections for errorB-step 6")



cB5_brain_yt <- correct_errorB.tbl_brain(cB4_brain_yt)
print_one_plot(x = cB5_brain_yt,  title = "Youtoo Sample #15 - After 5 corrections for errorB-step 7")


#errors happened here
cB6_brain_yt <- correct_errorB.tbl_brain(cB5_brain_yt)
print_one_plot(x = cB6_brain_yt,  title = "Youtoo Sample #15 - After 6 corrections for errorB-step 8")


cB7_brain_yt <- correct_errorB.tbl_brain(cB6_brain_yt)
print_one_plot(x = cB7_brain_yt,  title = "Youtoo Sample #15 - After 7 corrections for errorB-step 9")

is_errorB.tbl_brain(cB8_brain_yt)
```

# pipeline
```{r}
#start with brain data that is tidied and pca reoriented
ro_brain_yt <- ro_brain_ls_yt[[2]]


pipeline <- function(x = ro_brain_yt){
  #check for error A
  is_errorA(ro_brain_yt)

  cA_ro_brain_yt <- correct_errorA(ro_brain_yt, threshold.n=0.5)

}
```


