---
title: "rotation_calculation_experiment"
author: "Ziwei Crystal Zang"
date: "10/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

functions 
```{r}

#' @title create rotation matrix
#' @description creat 3 by 3 rotation matrix for error B correction
#' @param 
#' @param axis the axis that you are rotating around

#' @export
#' @examples
#' degree = 45
#' radian = deg2rad(degree)
#' ro_matrix <- create_ro_matrix(radian, axis = "y")
create_ro_matrix <- function(rotation_angle_radian, axis = "x"){
  if(axis == "x"){
    matrix.x <- diag(3)
    matrix.x[2,2] <- cos(rotation_angle_radian)
    matrix.x[2,3] <- -sin(rotation_angle_radian)
    matrix.x[3,2] <- sin(rotation_angle_radian)
    matrix.x[3,3] <- cos(rotation_angle_radian)
    message("rotate around x axis")
    return(matrix.x)
  } else if (axis == "y"){
    matrix.x <- diag(3)
    matrix.x[1,1] <- cos(rotation_angle_radian)
    matrix.x[1,3] <- sin(rotation_angle_radian)
    matrix.x[3,1] <- -sin(rotation_angle_radian)
    matrix.x[3,3] <- cos(rotation_angle_radian)
    message("rotate around y axis")
    return(matrix.x)
  }else if (axis == "z"){
    matrix.x <- diag(3)
    matrix.x[1,1] <- cos(rotation_angle_radian)
    matrix.x[2,1] <- sin(rotation_angle_radian)
    matrix.x[1,2] <- -sin(rotation_angle_radian)
    matrix.x[2,2] <- cos(rotation_angle_radian)
    message("rotate around z axis")
    return(matrix.x)
  }
}


```


```{r}
degree <- 45
radian <- deg2rad(degree)

ro_matrix <- create_ro_matrix(radian, axis="y")

data <- c(1,0,-1)%>%
  t()

data %*% ro_matrix
  
```

